ATTRIBUTES_ALL = [
    "cruel",
    "deceitful",
    "treacherous",
    "rude",
    "arrogant",
    "quarrelsome",
    "revengeful",
    "conceited",
    "humorless",
    "boastful",
    "quick-tempered",
    "pugnacious",
    "argumentative",
    "stubborn",
    "mercenary",
    "aggressive",
    "stolid",
    "quiet",
    "reserved",
    "gregarious",
    "pleasure-loving",
    "sensitive",
    "suave",
    "happy-go-lucky",
    "passionate",
    "jovial",
    "faithful",
    "courteous",
    "generous",
    "kind",
    "honest",
    "unreliable",
    "sly",
    "ignorant",
    "stupid",
    "lazy",
    "naive",
    "frivolous",
    "shrewd",
    "methodical",
    "scientifically-minded",
    "persistent",
    "practical",
    "ambitious",
    "alert",
    "industrious",
    "efficient",
    "sophisticated",
    "intelligent",
    "brilliant",
    "cowardly",
    "dirty",
    "gluttonous",
    "slovenly",
    "evasive",
    "materialistic",
    "suspicious",
    "ostentatious",
    "loud",
    "superstitious",
    "imitative",
    "suggestible",
    "radical",
    "impulsive",
    "grasping",
    "nationalistic",
    "conventional",
    "conservative",
    "ponderous",
    "talkative",
    "religious",
    "tradition-loving",
    "individualistic",
    "meditative",
    "straightforward",
    "progressive",
    "sensual",
    "neat",
    "sportsmanlike",
    "loyal",
    "musical",
    "artistic",
    "imaginative",
    "witty"
]

FAVORABILITIES_ALL = [
    -1.81,
    -1.66,
    -1.59,
    -1.46,
    -1.32,
    -1.27,
    -1.24,
    -1.18,
    -1.17,
    -1.14,
    -1.10,
    -0.99,
    -0.81,
    -0.78,
    -0.64,
    -0.58,
    -0.08,
    0.03,
    0.04,
    0.38,
    0.57,
    0.66,
    0.69,
    0.75,
    1.02,
    1.10,
    1.22,
    1.32,
    1.44,
    1.46,
    1.58,
    -1.42,
    -0.72,
    -1.75,
    -1.63,
    -1.32,
    -0.91,
    -0.87,
    0.20,
    0.42,
    0.87,
    0.87,
    0.87,
    0.90,
    0.95,
    1.09,
    1.12,
    1.15,
    1.52,
    1.86,
    -1.52,
    -1.49,
    -1.36,
    -1.21,
    -1.08,
    -1.06,
    -1.05,
    -0.80,
    -0.65,
    -0.58,
    -0.55,
    -0.53,
    -0.41,
    -0.37,
    -0.31,
    -0.18,
    -0.15,
    -0.12,
    0.08,
    0.10,
    0.15,
    0.39,
    0.50,
    0.69,
    0.77,
    0.80,
    0.84,
    0.85,
    1.04,
    1.08,
    1.08,
    1.12,
    1.33,
    1.38
]

ATTRIBUTES_KATZ = [
    "superstitious",
    "lazy",
    "happy-go-lucky",
    "ignorant",
    "musical",
    "ostentatious",
    "religious",
    "stupid",
    "dirty",
    "naive",
    "slovenly",
    "unreliable"
]

SCORES_KATZ = [
    84.0,
    75.0,
    38.0,
    38.0,
    26.0,
    26.0,
    24.0,
    22.0,
    17.0,
    14.0,
    13.0,
    12.0
]

ATTRIBUTES_GILBERT = [
    "superstitious",
    "lazy",
    "happy-go-lucky",
    "ignorant",
    "musical",
    "ostentatious",
    "religious",
    "stupid",
    "pleasure-loving"
]

SCORES_GILBERT = [
    41.0,
    31.0,
    17.0,
    24.0,
    33.0,
    11.0,
    17.0,
    10.0,
    19.0
]

ATTRIBUTES_KARLINS = [
    "superstitious",
    "lazy",
    "happy-go-lucky",
    "ignorant",
    "musical",
    "ostentatious",
    "religious",
    "stupid",
    "dirty",
    "naive",
    "slovenly",
    "unreliable",
    "pleasure-loving",
    "sensitive",
    "gregarious",
    "talkative",
    "imitative"
]

SCORES_KARLINS = [
    13.0,
    26.0,
    27.0,
    11.0,
    47.0,
    25.0,
    8.0,
    4.0,
    3.0,
    4.0,
    5.0,
    6.0,
    26.0,
    17.0,
    17.0,
    14.0,
    13.0
]

ATTRIBUTES_MADON = [
    "superstitious",
    "lazy",
    "happy-go-lucky",
    "ignorant",
    "musical",
    "ostentatious",
    "religious",
    "stupid",
    "dirty",
    "naive",
    "slovenly",
    "unreliable",
    "pleasure-loving",
    "sensitive",
    "gregarious",
    "talkative",
    "imitative",
    "loyal",
    "loud",
    "tradition-loving",
    "aggressive",
    "artistic",
    "quick-tempered",
    "revengeful",
    "rude",
    "quarrelsome",
    "sportsmanlike",
    "intelligent",
    "materialistic",
    "passionate",
    "straightforward"
]

SCORES_MADON = [
    1.7+5.3,
    12.1+10.5,
    0.0+7.9,
    10.3+13.2,
    27.6+39.5,
    8.6+5.3,
    19.0+13.2,
    1.7+0.0,
    0.0+0.0,
    1.7+0.0,
    3.5+7.9,
    5.2+5.3,
    5.2+0.0,
    5.2+0.0,
    6.9+5.3,
    10.3+13.2,
    1.7+0.0,
    22.4+13.2,
    20.7+52.6,
    20.7+7.9,
    15.5+18.4,
    13.8+5.3,
    13.8+15.8,
    13.8+5.3,
    13.8+26.3,
    8.6+18.4,
    12.1+15.8,
    3.5+13.2,
    8.6+13.2,
    8.6+13.2,
    12.1+13.2  
]

ATTRIBUTES_BERGSIEKER = [
    "cruel",
    "deceitful",
    "treacherous",
    "rude",
    "arrogant",
    "quarrelsome",
    "revengeful",
    "conceited",
    "humorless",
    "boastful",
    "quick-tempered",
    "pugnacious",
    "argumentative",
    "stubborn",
    "mercenary",
    "aggressive",
    "stolid",
    "quiet",
    "reserved",
    "gregarious",
    "pleasure-loving",
    "sensitive",
    "suave",
    "happy-go-lucky",
    "passionate",
    "jovial",
    "faithful",
    "courteous",
    "generous",
    "kind",
    "honest",
    "unreliable",
    "sly",
    "ignorant",
    "stupid",
    "lazy",
    "naive",
    "frivolous",
    "shrewd",
    "methodical",
    "scientifically-minded",
    "persistent",
    "practical",
    "ambitious",
    "alert",
    "industrious",
    "efficient",
    "sophisticated",
    "intelligent",
    "brilliant",
    "cowardly",
    "dirty",
    "gluttonous",
    "slovenly",
    "evasive",
    "materialistic",
    "suspicious",
    "ostentatious",
    "loud",
    "superstitious",
    "imitative",
    "suggestible",
    "radical",
    "impulsive",
    "grasping",
    "nationalistic",
    "conventional",
    "conservative",
    "ponderous",
    "talkative",
    "religious",
    "tradition-loving",
    "individualistic",
    "meditative",
    "straightforward",
    "progressive",
    "sensual",
    "neat",
    "sportsmanlike",
    "loyal",
    "musical",
    "artistic",
    "imaginative",
    "witty"
]

SCORES_BERGSIEKER = [
    1.5,
    2.2,
    1.5,
    5.9,
    3.0,
    6.7,
    3.0,
    2.2,
    1.5,
    6.7,
    8.1,
    3.0,
    3.7,
    3.7,
    1.5,
    17.8,
    1.5,
    3.7,
    1.5,
    12.6,
    9.6,
    3.7,
    3.0,
    2.2,
    13.3,
    8.9,
    11.9,
    3.0,
    5.9,
    8.1,
    6.7,
    5.9,
    3.0,
    8.9,
    3.7,
    11.1,
    2.2,
    3.0,
    2.2,
    2.2,
    1.5,
    5.2,
    3.7,
    7.4,
    5.2,
    4.4,
    1.5,
    1.5,
    5.2,
    1.5,
    1.5,
    1.5,
    2.2,
    2.2,
    3.0,
    12.6,
    5.9,
    7.4,
    35.6,
    3.0,
    2.2,
    2.2,
    3.0,
    11.1,
    2.2,
    2.2,
    1.5,
    2.2,
    1.5,
    21.5,
    20.0,
    5.9,
    8.1,
    3.0,
    9.6,
    8.9,
    5.9,
    1.5,
    17.0,
    30.4,
    20.0,
    11.1,
    6.7,
    5.9
]

GSS_OCCUPATIONS = [
    "Accountant",
    "Actor",
    "Actress",
    "Actuary for an Insurance Company",
    "Acupuncturist",
    "Addressing-Machine Operator",
    "Administrative Assistant",
    "Advertising Executive",
    "Advertising Salesman",
    "Aerobics Instructor",
    "Aeronautical Engineer",
    "Agricultural Fruit Inspector for Insect Control",
    "Agricultural Research Director",
    "Agricultural Research Engineer",
    "Aide on a Land Survey Crew",
    "Air Conditioning Mechanic",
    "Air Traffic Controller",
    "Aircraft Electrician",
    "Aircraft Riveter",
    "Airline flight attendant",
    "Airline Flight Engineer",
    "Airline Ground Crew Chief",
    "Airline Pilot",
    "Airline Refueler",
    "Airline Ticket Agent",
    "Airplane Mechanic",
    "Airport Security Screener",
    "Ambulance Driver",
    "Animal Shelter Worker",
    "Animal Trapper",
    "Animal-Control Officer",
    "Apartment Building Manager",
    "App Designer",
    "Apprentice Electrician",
    "Apprentice Plumber",
    "Apprentice Sheet Metalsmith",
    "Apprentice to a Machinist",
    "Apprentice to a Master Craftsman",
    "Architect",
    "Army Private",
    "Artificial Limb Fitter",
    "Assembly Line Worker",
    "Astronaut",
    "Attendant in an Ice-Skating Rink",
    "Auctioneer",
    "Author",
    "Auto Wrecker",
    "Autobody Repairer",
    "Automobile Dealer",
    "Automobile Mechanic",
    "Automobile Painter",
    "Automobile Repairman",
    "Automobile Repairwoman",
    "Backhoe Operator",
    "Bail Bond Provider",
    "Bailing-Machine Operator",
    "Baker",
    "Ballet Dancer",
    "Bank Examiner",
    "Bank Teller",
    "Banker",
    "Barber",
    "Bartender",
    "Battery Assembler",
    "Beauty Operator",
    "Beer Maker",
    "Bell Boy in a Hotel",
    "Betting Clerk",
    "Bicycle Messenger",
    "Bicycle Repairer",
    "Bill Collector",
    "Billing Clerk",
    "Billing-Machine Operator",
    "Biologist",
    "Biomedical Engineer",
    "Blackjack Dealer",
    "Black-Top-Machine Operator",
    "Blast Furnace Helper in a Steel Mill",
    "Blasting Powder Carrier in a Mine",
    "Boardinghouse Keeper",
    "Boilermaker",
    "Bookbinding Machine Operator",
    "Bookkeeper",
    "Boom Operator at a Marine Loading Dock",
    "Border Patrol Agent",
    "Bottle Capping Machine Operator",
    "Bottled-Water Delivery Driver",
    "Bottle-Washing-Machine Operator",
    "Box-Folding-Machine Operator",
    "Branch Manager of a Bank",
    "Bricklayer",
    "Bridal Consultant",
    "Bridge Ironworker",
    "Brokerage Clerk",
    "Budget Examiner",
    "Building Contractor",
    "Bulldozer Mechanic",
    "Burglar Alarm Installer",
    "Bus Driver",
    "Business Entrepreneur",
    "Business Services Sales Representative",
    "Businessman",
    "Butcher in a Store",
    "Cabinet Maker",
    "Cable TV Installer",
    "Cafeteria Supervisor",
    "Camp Counselor",
    "Campaign Fundraiser",
    "Canal Barge Pilot",
    "Car Alarm Installer",
    "Car Rental Agent",
    "Cargo Router",
    "Cargo Supervisor for an Airline",
    "Carpenter's Helper",
    "Carpet Cutter for a Rug Manufacturer",
    "Carpet Cutter in a Rug Store",
    "Carpet Layer",
    "Car-Tester for an Automobile Factory",
    "Carwash Attendant",
    "Caseworker Aide",
    "Cash Register Repairman",
    "Cashier in a Supermarket",
    "Cashier Supervisor",
    "Casino Cashier",
    "Casino Manager",
    "Casino Slots Supervisor",
    "Cattle Brander",
    "Cattle Killer in a Slaughtering Plant",
    "Cattle Rancher",
    "Cement Finisher",
    "Ceramic-Tile Setter",
    "Cheese Maker",
    "Chemical Engineer",
    "Chemical Laboratory Technician",
    "Chemist",
    "Chief Technology Officer",
    "Chiropractic Assistant",
    "Chiropractor",
    "Cigarette-Making Machine Operator",
    "Cinematographer",
    "City Planning Aide",
    "Civil Engineer",
    "Claims Clerk",
    "Classified Ad Taker for a Newspaper",
    "Cleaning Woman in Private Homes",
    "Clergyman",
    "Clerk in an Office",
    "Clerk Opening New Accounts at Bank",
    "Clinical Audiologist",
    "Cloth Dyer",
    "Coal Hauler Operator",
    "Coal Miner",
    "College Admissions Officer",
    "College or University President",
    "College Professor",
    "Colonel in the Army",
    "Combination Machine Tool Operator",
    "Commercial Artist",
    "Commercial Fisher",
    "Community Organization Worker",
    "Comparison Shopper for a Grocery Store",
    "Computer Hardware Engineer",
    "Computer Helpdesk Technician",
    "Computer Network Engineer",
    "Computer Programmer",
    "Computer Repairer",
    "Computer Room Supervisor for a Business Firm",
    "Computer Scientist",
    "Computer Security Analyst",
    "Computer Software Developer",
    "Computer Systems Analyst",
    "Computer Tape Librarian",
    "Computer Technician",
    "Computing Machine Operator",
    "Construction Foreman",
    "Construction Laborer",
    "Construction Riveter",
    "Conveyor-Belt Operator",
    "Cook in a Private Home",
    "Cook in a Restaurant",
    "Copy Editor",
    "Corporate Financial Analyst",
    "Corporate Meeting Planner",
    "Corporate Trainer",
    "Corrections Officers Supervisor",
    "Correspondence Clerk",
    "Cost Analyst",
    "Cotton Picker",
    "Counter Clerk in a Auto Parts Store",
    "Counter Clerk in a Fast Food Place",
    "County Agricultural Agent",
    "County Sheriff",
    "Court Bailiff",
    "Court Clerk",
    "Court Transcriber",
    "Crane-Crew Supervisor at a Port Facility",
    "Crating and Moving Estimator",
    "Credit Manager",
    "Credit Risk Analyst",
    "Credit-Card Record Clerk for a Department Store",
    "Crop-Duster Pilot",
    "Crude Oil Tester in a Petroleum Refinery",
    "Crushing-Machine Operator",
    "Currency Sorter in a Bank",
    "Custom Seamstress",
    "Customer-Complaint Clerk",
    "Customs Inspector",
    "Cutting Machine Operator",
    "Dairy Scientist",
    "Dairy Technologist",
    "Data Entry Clerk",
    "Database Security Administrator",
    "Day Care Aide",
    "Day Laborer",
    "Debt Management Counselor",
    "Deck Engineer on a Ship",
    "Deck Officer on a Commercial Fishing Boat",
    "Deep-Sea Diver",
    "Delicatessen Counter Clerk in a Grocery Store",
    "Dental Crown and Bridge Maker",
    "Dental Hygienist",
    "Dentist",
    "Dentist's Attendant",
    "Department Head in a State Government",
    "Desk Clerk in a Hotel",
    "Desktop Publishing Specialist",
    "Development Technician in a Factory",
    "Dialysis Technician",
    "Die Grinder",
    "Diesel Motor Mechanic",
    "Dietary Technician",
    "Dietitian in a Hospital",
    "Dirt Shoveler in a Mine",
    "Disc Jockey",
    "Dishwasher",
    "Disposal Plant Operator",
    "Ditch Digger",
    "Dog Groomer",
    "Donut Machine Operator",
    "Door Fitter in an Automobile Production Line",
    "Door-to-Door Salesman",
    "Dormitory Counselor",
    "Draftsman",
    "Drama Therapist",
    "Drawbridge Tender",
    "Dredge Operator",
    "Drilling Machine Operator in a Mine",
    "Drill-Press Operator",
    "Driver'S License Examiner",
    "Driving School Teacher",
    "Drug or Alcohol Rehabilitation Counselor",
    "Druggist",
    "Dry Cleaner",
    "Dynamite Blaster",
    "Economic Research Assistant",
    "Economist",
    "Egg Crate Packer",
    "Eldercare Aide",
    "Electric Motor Repairer",
    "Electric power lineman",
    "Electric Power Station Attendant",
    "Electrical Engineer",
    "Electrical Technician",
    "Electrician",
    "Electric-Meter Installer",
    "Electrolysis Operator",
    "Elevator Operator in a Building",
    "Elevator Repairer",
    "Elevator Safety Inspector",
    "Eligibility Interviewer for a Social Welfare Agency",
    "Embalmer",
    "Emergency Services Coordinator",
    "Employee Benefits Director",
    "Employee Benefits Specialist",
    "Employee Development Director",
    "Employment Clerk",
    "Engineer",
    "Engineering Design Manager",
    "Engineer's Aide",
    "Enlisted Man in the Army",
    "Envelope Stuffer",
    "Environmental Compliance Inspector",
    "Environmental Scientist",
    "Equipment Purchasing Agent",
    "Event Planner",
    "Executive Chef",
    "Exercise Therapist",
    "Faith Healer",
    "Farm Foreman",
    "Farm Laborer",
    "Farm Manager",
    "Farm Owner and Operator",
    "Farm Produce Buyer",
    "Fashion Designer",
    "Fashion Model",
    "Fax Machine Operator",
    "Fence Installer",
    "Fiber Machine Tender",
    "File Clerk",
    "Filling Station Attendant",
    "Film Editor",
    "Fingerprinter",
    "Fire Alarm Installer",
    "Fire Department Lieutenant",
    "Fire Inspector",
    "Fireman",
    "First Aid Nurse",
    "Fitter in a Shipyard",
    "Floor Refinisher",
    "Flour Miller",
    "Foam Machine Operator",
    "Food Processing Worker",
    "Foot Doctor",
    "Foreign Language Translator",
    "Foreman in a Factory",
    "Forester's Aide",
    "Forge Operator in a Steel Mill",
    "Fork-Lift Driver",
    "Fortune Teller",
    "Foundry Equipment Mechanic",
    "Freight Checker",
    "Freight Elevator Operator",
    "Freight Shipping Agent",
    "Funeral Director",
    "Funeral Home Assistant",
    "Funeral Home Director",
    "Furniture Refinisher",
    "Game Warden",
    "Gang Boss for a Mining Company",
    "Garbage Collector",
    "Gardener",
    "General contractor",
    "General Manager of a Manufacturing Plant",
    "General Manager of a Moving and Storage Company",
    "Geological Technician",
    "Geologist",
    "Gift Wrapper in a Department Store",
    "Glass Engraver",
    "Government Meat Grader",
    "Grain Farmer",
    "Grocery Bagger",
    "Ground Crew Supervisor in a Public Park",
    "Guidedog Trainer",
    "Hair Stylist",
    "Hand Lace Maker",
    "Hazardous Materials Removal Worker",
    "Head Cook",
    "Head Usher",
    "Hearing Aid Technician",
    "Heat-Sealing-Machine Operator",
    "Heavy-Equipment Operator on a Road Construction Job",
    "High School Teacher",
    "Highway Engineer",
    "Highway Maintenance Person",
    "Hog Raiser",
    "Home Improvement Salesperson",
    "Home Products Demonstrator",
    "Home Refrigerator Repairer",
    "Home-Care Aide for the Elderly",
    "Horse Breaker",
    "Horse Breeder",
    "Horse Stable Attendant",
    "Hospital Administrator",
    "Hospital Attendant",
    "Hospital-Admissions Officer",
    "Hotel Chambermaid",
    "House Carpenter",
    "House Painter",
    "House Parent in Institution",
    "Housekeeper in a Private Home",
    "Houseparent in a State Reformatory",
    "Human Resources Consultant",
    "Human Services Coordinator",
    "Importer",
    "Income-Tax Preparer",
    "Infantry Unit Leader",
    "Information Technology Systems Director",
    "Instructor in a School for the Handicapped",
    "Insulation Installer",
    "Insurance Agent",
    "Insurance Application Evaluator",
    "Insurance Claims Investigator",
    "Insurance Policy Information Clerk",
    "Insurance Sales Supervisor",
    "Insurance Underwriter",
    "Interior Decorator",
    "Irrigation Pump Installer",
    "Janitor",
    "Jazz Musician",
    "Jewelry Maker",
    "Jewelry Repairman",
    "Job Counselor",
    "Journalist",
    "Justice of a Municipal Court",
    "Key Maker",
    "Kitchen Steward",
    "Laborer in a Commercial Fish Hatchery",
    "Landlord",
    "Lathe Operator",
    "Laundress",
    "Law Clerk For Judge",
    "Lawn Mower Engine Repairer",
    "Lawyer",
    "Leaflet Distributor",
    "Lens Grinder",
    "Library Book Shelver",
    "Library Circulation Technician",
    "Licensed Practical Nurse",
    "Life Science Taxonomist",
    "Lifeguard",
    "Lime Kiln Operator",
    "Loan Officer",
    "Loan Processor for a Bank",
    "Lobbyist",
    "Local Delivery Truck Driver",
    "Local Official of a Labor Union",
    "Locksmith",
    "Locomotive Electrician",
    "Locomotive Engineer",
    "Locomotive Repairman",
    "Logger",
    "Logistics Planner",
    "Longshoreman",
    "Loom Fixer in a Textile Mill",
    "Loom Operator",
    "Lost-and-Found Clerk in a Department",
    "Lumber Stacker",
    "Lunchroom Operator",
    "Machine Assembler",
    "Machine Attendant in a Factory",
    "Machine Feeder in a Manufacturing Plant",
    "Machine Oiler",
    "Machine Operator in a Factory",
    "Machine Operator in a Shoe Factory",
    "Machine Operator in a Textile Mill",
    "Machine Set-up Man in a Factory",
    "Machinist",
    "Magazine Editor",
    "Mailman",
    "Mail-Order Clerk",
    "Mailroom Clerk for a Private Company",
    "Mailroom Supervisor for a Private Company",
    "Maitre D'",
    "Management Consultant",
    "Manager",
    "Manager for a Fast Food Franchise",
    "Manager for a Motel Chain",
    "Manager of a Cement Factory",
    "Manager of a Commercial Bakery",
    "Manager of a Local TV Station",
    "Manager of a Mail Order House",
    "Manager of a Movie Theater",
    "Manager of a Pulp Mill",
    "Manager of a Real Estate Office",
    "Manager of a Supermarket",
    "Manager of an Automobile Plant",
    "Manager of an Escort Service",
    "Manager of United Way Charity",
    "Manicurist",
    "Manufacturer's Representative",
    "Marine Engineer",
    "Market Research Interviewer",
    "Market Research Investigator",
    "Marketing Representative for a Manufacturing Firm",
    "Massage Therapist",
    "Masseur",
    "Masseuse",
    "Material Lister for a Construction Company",
    "Mathematical Engineering Technician",
    "Mathematician",
    "Mayor of a Large City",
    "Meat Cutter in a Meat Cutting Plant",
    "Meat Grader",
    "Mechanical Engineer",
    "Mechanical Trouble Shooter",
    "Mechanic's Helper",
    "Medical Technician",
    "Medical Transcriber",
    "Medical-Record Librarian in a Hospital",
    "Member of a City Council",
    "Member of a Rock Band",
    "Member of the Board of Directors of a Large Corporation",
    "Merchandise Buyer for a Department Store",
    "Merchant Seaman",
    "Metal Caster in a Foundry",
    "Metal Engraver",
    "Metal Plater",
    "Metal Solderer",
    "Metallurgical Engineer",
    "Metal-Stamping-Machine Operator",
    "Meteorologist",
    "Meter Maid",
    "Meter Reader for a Gas or Electric Company",
    "Midwife",
    "Migrant Worker",
    "Milk Tester",
    "Milliner",
    "Milling Machine Operator",
    "Millwright",
    "Mining Engineer",
    "Minister",
    "Mobile Home Installer",
    "Mobile Home Park Manager",
    "Mold Maker in Foundry",
    "Molding Machine Operator",
    "Motel Owner",
    "Motion Picture Projectionist",
    "Museum Curator",
    "Museum Security Chief",
    "Musician in a Symphony Orchestra",
    "My Own Occupation",
    "Mystery Shopper",
    "Narcotics Investigator",
    "Natural Childbirth and Infant Care Instructor",
    "Network Administrator",
    "Network Support Technician",
    "Newspaper Peddler",
    "Newspaper Proofreader",
    "Nuclear Plant Operator",
    "Nuclear Technician",
    "Nurse Anesthetist",
    "Nurse Practitioner",
    "Nursery School Teacher",
    "Nut Roaster",
    "Obstetrician/Gynecologist",
    "Occupational Rehabilitation Aide",
    "Occupational Therapist",
    "Office Helper for a Hospital",
    "Office Supervisor",
    "Office Systems Analyst",
    "Oil Exploration Engineer",
    "Oil Refining Equipment Operator",
    "Oil Rig Worker",
    "Oil Well Pumper",
    "Oil-Well Driller",
    "Operations Analyst",
    "Optician",
    "Optometrist",
    "Orange Grove Picker",
    "Orange Grower",
    "Order Expediter for a Wholesale Business",
    "Ore Train Motorman",
    "Organizer for a Religious Crusade",
    "Orthopedic Brace Maker",
    "Owner of a Bowling Alley",
    "Owner of a Check Cashing Service",
    "Owner of a Computer Software Company",
    "Owner of a Day Care Center",
    "Owner of a Filling Station and Garage",
    "Owner of a Local Bus Company",
    "Owner of a Local Radio Station",
    "Owner of a Mail Order House",
    "Owner of a Manufacturing Plant",
    "Owner of an Apparel Factory",
    "Owner of an Art Gallery",
    "Owner-Operator of a Printing Shop",
    "Oxygen Therapist",
    "Packer in a Wholesale Vegetable Market",
    "Paid Campaign Staff Member",
    "Panhandler",
    "Paper Embossing Machine Operator",
    "Paper Tester in a Pulp Mill",
    "Paperhanger",
    "Paper-Making Machine Tender",
    "Para-Legal",
    "Paramedic",
    "Park Superintendent",
    "Parking Enforcement Officer",
    "Parking Lot Attendant",
    "Parole Officer",
    "Party Caterer",
    "Passenger Service Representative",
    "Pathology Technician",
    "Pattern Maker in a Metal Shop",
    "Payroll Clerk",
    "Payroll Supervisor",
    "Pedicab Operator",
    "Personal Financial Planner",
    "Personnel Director",
    "Personnel Recruiter",
    "Pharmaceutical Representative",
    "Pharmacist",
    "Pharmacist Technician",
    "Photo-Booth Operator",
    "Photocopying-Machine Operator",
    "Photoengraver",
    "Photograph Developer",
    "Photographer",
    "Physical Therapist",
    "Physical Therapy Assistant",
    "Physician",
    "Physician's Assistant",
    "Physicist",
    "Piano Tuner",
    "Pile-Driver Operator",
    "Pill Machine Operator in a Pharmaceutical Plant",
    "Plaster Mold Maker",
    "Plasterer",
    "Playground Director",
    "Playground Monitor",
    "Plumber",
    "Podiatrist",
    "Poker Room Supervisor",
    "Pole Climber for a Telephone Company",
    "Police Lieutenant",
    "Police Officer",
    "Policeman",
    "Pollution Control Engineer",
    "Post Office Clerk",
    "Post Office Mail Sorter",
    "Postmaster",
    "Potato Chip Fryer",
    "Potato-Chip-Sacking-Machine Operator",
    "Poultry Raiser",
    "Power Crane Operator",
    "Power Plant Operator",
    "Preparer of Clothing Patterns",
    "Prescription Clerk",
    "Priest",
    "Printing Press Operator",
    "Prison Guard",
    "Private Detective",
    "Professional Athlete",
    "Professional Babysitter",
    "Professionally Trained Forester",
    "Professionally Trained Health Therapist",
    "Professionally Trained Librarian",
    "Professor of Biology in a College or University",
    "Professor of Business Administration in a College or University",
    "Professor of English in a College or University",
    "Professor of History in a College or University",
    "Professor of Physics in a College or University",
    "Professor of Psychology in a College or University",
    "Proprietor of a Shoe Repair Shop",
    "Prosthetic Aide",
    "Psychiatrist",
    "Psychologist",
    "Public Grade School Teacher",
    "Public Health Analyst",
    "Public Health Educator in a Clinic",
    "Public Opinion Pollster",
    "Public Relations Director",
    "Public Relations specialist",
    "Public Safety Director",
    "Public-Address Announcer at a Train Station",
    "Pump Operator",
    "Pump-House Engineer",
    "Purchasing Clerk",
    "Purchasing Manager for a Business",
    "Pushcart Vendor",
    "Quality Checker in a Manufacturing Plant",
    "Quality Control Engineer",
    "Radiation Control Engineer in a Power Plant",
    "Radiation Therapist",
    "Radio operator",
    "Radio Tester",
    "Rail Track Repairer",
    "Railroad Conductor",
    "Railroad Detective",
    "Railroad Signal Mechanic",
    "Railroad Signal-Tower Operator",
    "Railroad Switchman",
    "Railroad Ticket Agent",
    "Railway Equipment Operator",
    "Real Estate Agent",
    "Real Estate Appraiser",
    "Rebar (Reinforcing Iron Bar) Worker",
    "Receptionist",
    "Record Keeper",
    "Refrigerating Machine Operator",
    "Regional Manager for a Bus Company",
    "Registered Nurse",
    "Resource Management Director",
    "Restaurant Critic for a Newspaper",
    "Restaurant Hostess",
    "Restaurant Owner",
    "Rolling Mill Operator in a Metal Shop",
    "Roof Bolter In Mine",
    "Roofer",
    "Rubber Mold Maker",
    "Rubber-Stamp Maker",
    "RV (Recreational Vehicle) Mechanic",
    "Sailor in Navy",
    "Salad Maker in a Hotel Kitchen",
    "Sales Clerk in a Store",
    "Sales Engineer",
    "Salesperson in a Furniture Store",
    "Salesperson in a Hardware Store",
    "Salesperson in a Shoe Store",
    "Salesperson in a Store",
    "Salesperson in an Appliance Store",
    "Saloonkeeper",
    "Sample Collector in a Chemical Plant",
    "Sample Collector in a Pulp Mill",
    "Sandfill Operator in a Mine",
    "Satellite Communications Operator",
    "Sausage Mixer",
    "Saw Sharpener",
    "Scaffold Builder",
    "Scale Attendant",
    "School Counselor",
    "School Principal",
    "School Superintendent",
    "School-Crossing Guard",
    "Scrap Sorter in a Shoe Factory",
    "Secret Service Agent",
    "Secretary",
    "Security Guard in a Bank",
    "Seed Analyst",
    "Seismic Observer of Earthquakes",
    "Semiconductor Assembler",
    "Semi-Skilled Worker",
    "Septic Tank Cleaner",
    "Sergeant",
    "Service Station Manager",
    "Sewing Machine Assembler",
    "Sewing Machine Operator",
    "Sheet-Metal Duct Installer",
    "Sheet-Rock Installer",
    "Shelf Stocker in a Grocery Store",
    "Ship Fitter Apprentice",
    "Ship Steward",
    "Shipping Clerk",
    "Ship's Captain",
    "Shoemaker",
    "Shoeshiner",
    "Short-Order Cook",
    "Sightseeing Guide",
    "Sign Painter",
    "Skilled Craftsman in a Factory",
    "Skilled Craftsman in a Metalworking Shop",
    "Skip-Hoist Operator",
    "Skycap",
    "Slot Machines Operations Director",
    "Social Scientist",
    "Social Security Administrator",
    "Social Worker",
    "Sociologist",
    "Soda Jerk",
    "Solar Panel Installer",
    "Soldier",
    "Sound Mixer in a Television Station",
    "Special Education Teacher",
    "Speech Therapist",
    "Spotlight Operator",
    "Spray Painter in a Manufacturing Plant",
    "Stapling-Machine Operator in a Furniture Factory",
    "Statistical Clerk",
    "Statistician",
    "Steam Boiler Fireman",
    "Steam Cleaner for a Used Car Lot",
    "Steam Presser in a Garment Factory",
    "Steam-Shovel Operator",
    "Steel Rigger on a Construction Job",
    "Steel Temperer",
    "Stencil Cutter",
    "Stenographer",
    "Stock and Bond Salesman",
    "Stock Taker in a Department Store",
    "Stockroom Attendant",
    "Stockroom Manager",
    "Street Corner Drug Dealer",
    "Street sweeper",
    "Street-Sweeper Operator",
    "Student Admissions Clerk",
    "Subway Operator",
    "Superintendent of a Construction Job",
    "Supervisor in a Auto Repair Shop",
    "Supervisor in a Logging Operation",
    "Supervisor in a Machine Shop",
    "Supervisor of a Branch Telephone Exchange",
    "Supervisor of a Janitorial Service",
    "Supervisor of a Truck Delivery Service",
    "Supervisor of Skilled Craftsmen",
    "Surgeon",
    "Surveyor",
    "Swap Meet Vendor",
    "Table Clearer in a Restaurant",
    "Tailor",
    "Tank Crew Member",
    "Tax Collector",
    "Taxicab Driver",
    "Teacher's Aide in an Elementary School",
    "Technician",
    "Technician Drawing Blood",
    "Telegraph Operator",
    "Telephone Installer",
    "Telephone Operator",
    "Telephone Solicitor",
    "Telephone-Answering-Service Operator",
    "Temporary Clerk in an Office",
    "Tenant Farmer",
    "Termite Exterminator",
    "Theater Usher",
    "Theatrical Agent",
    "Timber Buyer for a Pulp Mill",
    "Time-Motion Analyst",
    "Tire Retreader",
    "Tire-Mold Engraver",
    "Toll Bridge Collector",
    "Tombstone Carver",
    "Tool and Die Maker",
    "Tool Programmer in a Manufacturing Plant",
    "Tool Sharpener",
    "Toolroom Helper in a Chain Saw Factory",
    "Toy Manufacturer",
    "Trailer Truck Driver",
    "Train Attendant",
    "Transit Authority Police",
    "Trash Hauler",
    "Travel Agent",
    "Traveling Salesman for a Wholesale Concern",
    "Tree Surgeon",
    "Truck Dispatcher",
    "Truck Driver's Helper",
    "Turpentine Distiller",
    "TV Anchor",
    "TV Announcer",
    "TV Director",
    "TV Repairman",
    "Typesetter",
    "Typist",
    "Union Organizer",
    "Unskilled Worker in a Factory",
    "Upholsterer",
    "Urban Planner",
    "Used Car Salesman",
    "Vending Machine Coin Collector",
    "Veneer Glue Spreader",
    "Veterinarian",
    "Veterinarian Assistant",
    "Video Game Repairer in Arcade",
    "Waiter in a Restaurant",
    "Waitress in a Restaurant",
    "Warehouse Hand",
    "Watch Assembler",
    "Watch-Crystal Grinder",
    "Water Well Driller",
    "Water Well Drilling Roughneck",
    "Water-Pollution Specialist",
    "Web Designer",
    "Weight Station Operator",
    "Welder",
    "Wildlife Officer",
    "Wildlife Technician",
    "Wind Turbine Mechanic",
    "Window Display Artist",
    "Window Glass Installer",
    "Windshield Installer",
    "Wire Pulling Machine Operator",
    "Wood Carver",
    "Wood Lathe Operator",
    "Wood Miller",
    "Wood Technologist",
    "Wood-Model Maker",
    "Word Processor",
    "Writer of Technical Manuals",
    "X-ray Technician",
    "Yarn Spinner in a Textile Mill",
    "Yeast Maker"
]

GSS_PRESTIGE_RATINGS = [
    5.7,
    5.7,
    5.5,
    5.0,
    4.5,
    3.5,
    4.8,
    5.4,
    4.1,
    3.9,
    6.9,
    5.2,
    6.0,
    6.3,
    3.7,
    4.6,
    6.2,
    5.7,
    4.6,
    4.6,
    6.2,
    4.8,
    6.6,
    4.6,
    4.0,
    5.5,
    4.4,
    4.6,
    4.1,
    3.3,
    4.1,
    4.3,
    5.5,
    4.6,
    4.3,
    3.8,
    4.0,
    4.1,
    6.7,
    4.9,
    5.4,
    3.7,
    7.4,
    2.6,
    3.9,
    6.3,
    3.2,
    4.3,
    4.3,
    4.7,
    4.1,
    4.6,
    4.6,
    4.3,
    4.2,
    3.9,
    4.6,
    4.9,
    5.3,
    4.2,
    6.1,
    4.0,
    3.6,
    3.8,
    4.0,
    3.7,
    3.0,
    2.9,
    3.3,
    3.3,
    3.0,
    4.3,
    4.2,
    6.9,
    6.9,
    2.9,
    3.7,
    3.5,
    3.7,
    3.2,
    3.9,
    3.6,
    4.6,
    4.7,
    5.3,
    3.0,
    3.1,
    2.8,
    3.2,
    5.7,
    4.2,
    3.7,
    4.8,
    4.8,
    4.9,
    5.4,
    4.3,
    4.1,
    3.9,
    5.8,
    4.5,
    5.5,
    3.7,
    4.4,
    3.6,
    4.1,
    3.8,
    4.1,
    4.8,
    3.5,
    3.0,
    3.9,
    4.3,
    3.3,
    3.3,
    3.1,
    3.5,
    4.3,
    2.9,
    4.5,
    3.8,
    3.4,
    3.8,
    3.4,
    4.6,
    3.7,
    2.9,
    2.8,
    4.8,
    4.1,
    3.6,
    3.6,
    6.5,
    5.5,
    6.7,
    5.8,
    5.1,
    5.9,
    3.0,
    5.1,
    5.2,
    6.4,
    4.1,
    3.5,
    2.9,
    5.8,
    3.8,
    4.3,
    5.7,
    2.9,
    3.6,
    4.4,
    5.1,
    7.1,
    6.9,
    6.7,
    4.0,
    4.7,
    3.9,
    5.0,
    3.5,
    6.5,
    4.7,
    5.8,
    6.0,
    4.9,
    5.3,
    6.4,
    6.0,
    6.0,
    6.2,
    4.1,
    5.4,
    4.8,
    5.1,
    4.1,
    4.3,
    3.2,
    3.9,
    3.9,
    4.6,
    5.6,
    5.2,
    5.2,
    5.5,
    3.7,
    5.4,
    2.5,
    3.4,
    2.8,
    5.0,
    5.9,
    4.4,
    5.0,
    4.8,
    4.9,
    3.6,
    4.9,
    5.1,
    3.4,
    4.5,
    4.7,
    3.2,
    3.9,
    4.4,
    3.6,
    4.9,
    3.5,
    5.5,
    5.0,
    4.0,
    5.5,
    3.6,
    3.0,
    4.8,
    5.0,
    4.3,
    5.0,
    3.5,
    5.3,
    5.3,
    6.7,
    4.8,
    6.6,
    3.5,
    4.8,
    4.7,
    5.5,
    3.9,
    4.4,
    5.2,
    5.4,
    3.5,
    4.0,
    2.8,
    4.2,
    2.7,
    3.3,
    2.8,
    4.2,
    2.9,
    3.9,
    4.8,
    4.4,
    3.6,
    4.1,
    4.1,
    4.3,
    4.1,
    4.2,
    4.8,
    5.8,
    3.0,
    4.5,
    5.4,
    6.0,
    2.6,
    4.9,
    4.2,
    5.2,
    4.2,
    6.7,
    5.3,
    5.2,
    4.2,
    3.9,
    3.2,
    4.3,
    4.9,
    5.0,
    4.5,
    5.9,
    5.2,
    5.2,
    5.7,
    3.9,
    6.6,
    5.9,
    5.0,
    5.3,
    2.5,
    5.4,
    6.5,
    4.4,
    4.5,
    5.7,
    4.9,
    3.5,
    4.7,
    3.5,
    5.0,
    5.2,
    4.6,
    5.4,
    5.3,
    3.2,
    3.3,
    3.7,
    3.5,
    3.1,
    5.2,
    3.9,
    4.5,
    6.2,
    5.5,
    5.7,
    5.6,
    3.8,
    3.7,
    3.2,
    3.4,
    3.8,
    6.3,
    5.5,
    4.9,
    4.4,
    4.1,
    3.8,
    2.6,
    4.4,
    3.4,
    3.2,
    4.3,
    4.9,
    4.4,
    5.5,
    3.9,
    4.9,
    4.2,
    3.8,
    3.5,
    5.0,
    5.4,
    3.8,
    6.0,
    6.3,
    3.1,
    4.2,
    4.3,
    4.9,
    2.8,
    3.9,
    4.6,
    3.8,
    3.8,
    4.8,
    4.0,
    3.4,
    4.8,
    4.3,
    4.5,
    6.1,
    6.0,
    4.3,
    3.5,
    3.7,
    3.4,
    3.9,
    5.1,
    3.6,
    4.3,
    3.1,
    6.6,
    4.6,
    5.6,
    2.8,
    4.6,
    3.9,
    4.4,
    3.5,
    4.0,
    5.4,
    4.8,
    4.6,
    5.1,
    5.9,
    5.7,
    5.6,
    3.7,
    4.8,
    4.1,
    4.7,
    4.2,
    4.8,
    4.5,
    4.8,
    3.9,
    3.0,
    5.6,
    4.5,
    4.3,
    4.6,
    5.5,
    6.9,
    3.1,
    3.7,
    3.4,
    4.7,
    3.9,
    3.3,
    5.7,
    3.8,
    6.4,
    2.9,
    4.3,
    3.2,
    3.9,
    6.5,
    4.8,
    4.1,
    4.1,
    4.5,
    4.9,
    4.2,
    4.2,
    4.5,
    4.1,
    5.5,
    5.7,
    4.9,
    3.8,
    5.0,
    3.8,
    3.7,
    3.4,
    3.1,
    3.0,
    3.4,
    3.9,
    3.7,
    3.3,
    3.4,
    4.3,
    3.5,
    3.8,
    4.1,
    4.4,
    5.5,
    4.7,
    3.9,
    3.7,
    4.2,
    3.6,
    4.9,
    5.2,
    4.6,
    5.0,
    4.5,
    4.7,
    5.8,
    4.2,
    3.6,
    4.1,
    5.2,
    4.9,
    5.5,
    3.3,
    5.5,
    3.5,
    4.6,
    6.3,
    5.0,
    5.6,
    5.2,
    4.3,
    3.6,
    3.7,
    4.0,
    6.2,
    6.2,
    7.2,
    3.6,
    3.7,
    6.6,
    4.5,
    3.4,
    5.7,
    4.9,
    4.9,
    5.6,
    4.1,
    6.9,
    4.5,
    4.5,
    3.7,
    4.3,
    3.7,
    3.9,
    6.0,
    4.2,
    5.9,
    3.2,
    4.4,
    5.0,
    2.7,
    3.7,
    3.5,
    3.8,
    3.7,
    5.8,
    6.3,
    4.0,
    3.3,
    4.0,
    4.0,
    4.9,
    4.1,
    5.3,
    4.2,
    5.6,
    5.4,
    2.9,
    5.6,
    4.9,
    5.8,
    5.0,
    2.9,
    4.5,
    6.3,
    7.0,
    6.4,
    6.6,
    5.3,
    2.9,
    7.0,
    5.1,
    5.9,
    4.3,
    5.0,
    5.2,
    6.0,
    4.9,
    4.6,
    4.4,
    5.1,
    5.1,
    5.8,
    6.6,
    3.2,
    4.6,
    4.5,
    3.7,
    4.0,
    5.3,
    4.5,
    4.0,
    6.2,
    4.9,
    4.8,
    5.1,
    5.0,
    4.4,
    6.3,
    5.6,
    5.5,
    4.8,
    5.9,
    3.1,
    4.3,
    2.1,
    4.1,
    3.7,
    3.5,
    3.7,
    5.1,
    6.0,
    4.6,
    3.4,
    2.4,
    4.8,
    3.9,
    3.9,
    5.9,
    4.9,
    4.3,
    4.7,
    3.3,
    6.0,
    5.2,
    4.4,
    5.7,
    6.7,
    5.6,
    3.1,
    3.3,
    3.8,
    3.9,
    4.8,
    6.2,
    5.4,
    7.6,
    6.0,
    6.9,
    3.7,
    3.9,
    4.4,
    3.3,
    3.3,
    4.2,
    3.2,
    4.7,
    6.1,
    3.3,
    4.3,
    6.4,
    5.9,
    6.0,
    5.8,
    4.6,
    4.0,
    5.8,
    2.9,
    3.0,
    4.0,
    4.9,
    5.2,
    4.3,
    4.5,
    6.3,
    4.0,
    4.2,
    5.0,
    6.2,
    4.2,
    4.6,
    5.9,
    5.4,
    6.9,
    6.9,
    6.3,
    6.5,
    7.2,
    7.0,
    3.9,
    4.9,
    6.6,
    6.4,
    5.8,
    6.0,
    5.9,
    3.9,
    5.1,
    5.1,
    5.3,
    3.4,
    3.4,
    4.9,
    3.9,
    5.0,
    2.8,
    4.7,
    6.0,
    6.3,
    6.2,
    4.5,
    3.8,
    4.4,
    5.1,
    4.8,
    4.9,
    4.4,
    4.8,
    3.4,
    4.8,
    4.9,
    5.4,
    3.9,
    4.1,
    4.4,
    3.8,
    5.1,
    6.5,
    5.6,
    4.6,
    3.7,
    5.2,
    4.0,
    4.0,
    3.9,
    3.8,
    2.8,
    4.2,
    5.8,
    2.7,
    3.7,
    5.1,
    3.6,
    3.3,
    3.3,
    3.9,
    3.5,
    3.6,
    4.6,
    3.5,
    3.6,
    5.5,
    3.4,
    3.1,
    3.8,
    3.7,
    5.8,
    6.5,
    6.2,
    4.1,
    3.0,
    6.7,
    4.6,
    3.7,
    4.2,
    6.3,
    4.1,
    4.0,
    3.4,
    5.9,
    4.4,
    3.4,
    3.6,
    3.8,
    3.8,
    2.8,
    4.2,
    4.4,
    3.9,
    6.1,
    3.7,
    2.6,
    3.3,
    3.5,
    3.3,
    4.9,
    4.9,
    3.6,
    3.7,
    3.9,
    6.2,
    5.7,
    5.3,
    6.1,
    2.3,
    4.4,
    6.1,
    4.5,
    6.0,
    5.7,
    3.3,
    3.7,
    3.3,
    4.2,
    5.4,
    4.7,
    3.0,
    3.6,
    4.3,
    4.5,
    4.3,
    3.3,
    4.3,
    5.6,
    3.4,
    3.0,
    4.0,
    1.9,
    3.0,
    3.3,
    4.4,
    4.0,
    5.2,
    4.5,
    5.0,
    5.1,
    4.3,
    4.0,
    4.7,
    5.2,
    7.7,
    4.6,
    2.8,
    2.3,
    4.4,
    4.1,
    4.1,
    3.2,
    4.9,
    5.1,
    5.1,
    3.8,
    4.3,
    3.6,
    2.5,
    3.1,
    2.9,
    3.9,
    3.9,
    2.6,
    4.6,
    4.1,
    4.9,
    2.8,
    3.5,
    3.3,
    3.9,
    4.1,
    5.1,
    2.8,
    3.1,
    4.4,
    4.4,
    4.2,
    5.0,
    3.6,
    4.1,
    3.5,
    4.0,
    3.7,
    3.4,
    3.4,
    5.8,
    5.2,
    5.6,
    4.0,
    3.9,
    3.8,
    4.6,
    2.8,
    3.8,
    5.5,
    3.5,
    3.1,
    3.1,
    6.4,
    4.5,
    3.4,
    3.6,
    3.6,
    3.2,
    3.8,
    3.6,
    4.4,
    4.1,
    5.5,
    5.4,
    3.9,
    4.2,
    5.0,
    4.8,
    4.9,
    4.0,
    3.8,
    3.1,
    4.0,
    3.9,
    4.1,
    4.0,
    4.4,
    4.1,
    4.2,
    5.4,
    5.7,
    3.0,
    3.8
]
